//>>built
define("./List,./_StoreMixin,dojo/_base/declare,dojo/_base/lang,dojo/_base/Deferred,dojo/on,./util/misc,put-selector/put".split(","),function(z,A,B,w,p,C,q,j){return B([z,A],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:2E3,rowHeight:22,queryRowsOverlap:1,pagingDelay:q.defaultDelay,postCreate:function(){this.inherited(arguments);var c=this;C(this.bodyNode,"scroll",q.throttleDelayed(function(f){c._processScroll(f)},null,this.pagingDelay))},renderQuery:function(c,
f,i){var b={query:c,count:0,node:f,options:i};if(!f){var g={node:j(this.contentNode,"div.dgrid-preload",{rowIndex:0}),count:0,query:c,next:b,options:i};b.node=f=j(this.contentNode,"div.dgrid-preload");b.previous=g}f.rowIndex=this.minRowsPerPage;(g=this.preload)?((b.next=g.next)&&this.bodyNode.scrollTop>=g.node.offsetTop?b.previous=g:(b.next=g,b.previous=g.previous),b.previous.next=b,b.next.previous=b):this.preload=b;var k=j(f,"-div.dgrid-loading");j(k,"div.dgrid-below",this.loadingMessage);var i=
w.mixin(this.get("queryOptions"),i,{start:0,count:this.minRowsPerPage,query:c}),l=c(i),d=this;p.when(this.renderArray(l,f,i),function(a){return p.when(l.total||l.length,function(c){j(k,"!");var i=a.length,c=c||i;if(!c)d.noDataNode=j(d.contentNode,"div.dgrid-no-data"),d.noDataNode.innerHTML=d.noDataMessage;for(var g=0,e=0;e<i;e++)g+=d._calcRowHeight(a[e]);if(i&&g)d.rowHeight=g/i;c-=i;b.count=c;f.rowIndex=i;c?f.style.height=Math.min(c*d.rowHeight,d.maxEmptySpace)+"px":f.style.display="none";d._processScroll();
return a})});return l},refresh:function(){this.inherited(arguments);if(this.store){var c=this;this._trackError(function(){return c.renderQuery(function(f){return c.store.query(c.query,f)})})}},_calcRowHeight:function(c){var f=c.previousSibling;return f&&f.offsetTop!=c.offsetTop?c.offsetHeight:0},lastScrollTop:0,_processScroll:function(c){function f(a,c,d,e){var h=b.farOffRemoval,f=a.node;if(c>2*h){for(var g,k=f[d],l=0,m=0,n=[];g=k;){var o=b._calcRowHeight(g);if(l+o+h>c||0>k.className.indexOf("dgrid-row")&&
0>k.className.indexOf("dgrid-loading"))break;var k=g[d],t,p=g.observerIndex;if(p!=t&&-1<t){var q=b.observers,r=q[t];r&&r.cancel();q[t]=0}l+=o;m+=g.count||1;t=p;b.removeRow(g,!0);n.push(g)}a.count+=m;e?(f.rowIndex-=m,i(a)):f.style.height=f.offsetHeight+l+"px";for(var s=j("div"),a=0;a<n.length;a++)j(s,n[a]);setTimeout(function(){j(s,"!")},1)}}function i(a,c){a.node.style.height=Math.min(a.count*b.rowHeight,c?Infinity:b.maxEmptySpace)+"px"}var b=this,g=b.bodyNode,c=c&&c.scrollTop||g.scrollTop,k=g.offsetHeight+
c,l,d,a=b.preload,q=b.lastScrollTop,v=b.bufferRows*b.rowHeight,x=v-b.rowHeight;for(b.lastScrollTop=c;a&&!a.node.offsetWidth;)a=a.previous;for(;a&&a!=l;){l=b.preload;b.preload=a;d=a.node;var e=d.offsetTop;if(k+1+x<e){do a=a.previous;while(a&&!a.node.offsetWidth)}else if(c-1-x>e+d.offsetHeight){do a=a.next;while(a&&!a.node.offsetWidth)}else{var h=((d.rowIndex?c-v:k)-e)/b.rowHeight,e=(k-c+2*v)/b.rowHeight,r=Math.max(Math.min((c-q)*b.rowHeight,b.maxRowsPerPage/2),b.maxRowsPerPage/-2),e=e+Math.min(Math.abs(r),
10);0==d.rowIndex&&(h-=e);h=Math.max(h,0);10>h&&0<h&&e+h<b.maxRowsPerPage&&(e+=Math.max(0,h),h=0);e=Math.min(Math.max(e,b.minRowsPerPage),b.maxRowsPerPage,a.count);if(0==e)break;var e=Math.ceil(e),h=Math.min(Math.floor(h),a.count-e),n=w.mixin(b.get("queryOptions"),a.options);a.count-=e;var m=d,s,u=b.queryRowsOverlap;if(r=0<d.rowIndex&&a){var o=a.previous;o&&(f(o,c-(o.node.offsetTop+o.node.offsetHeight),"nextSibling"),0<h&&o.node==d.previousSibling?(h=Math.min(a.count,h),a.previous.count+=h,i(a.previous,
!0),a.count-=h,d.rowIndex+=h,u=0):e+=h);n.start=d.rowIndex-u;d.rowIndex+=e}else{if(a.next)f(a.next,a.next.node.offsetTop-k,"previousSibling",!0),m=d.nextSibling,m==a.next.node?(a.next.count+=a.count-h,a.next.node.rowIndex=h+e,i(a.next),a.count=h,u=0):s=!0;n.start=a.count}n.count=Math.min(e+u,b.maxRowsPerPage);if(s)s=m.offsetTop;i(a);d=j(m,"-div.dgrid-loading[style=height:"+e*b.rowHeight+"px]");j(d,"div.dgrid-"+(r?"below":"above"),b.loadingMessage);d.count=e;n.query=a.query;var y=a.query(n);if(void 0===
b._trackError(function(){return y}))break;(function(a,c,d,e,f){p.when(b.renderArray(f,a,n),function(){m=a.nextSibling;j(a,"!");if(e&&m){var c=b.getScrollPosition();b.scrollTo({x:c.x,y:c.y+m.offsetTop-e,preserveMomentum:!0})}d&&p.when(f.total||f.length,function(a){d.count=a-d.node.rowIndex;i(d)});b._processScroll()})}).call(this,d,g,r,s,y);a=a.previous}}}})});