//>>built
define("dojo/_base/lang,dojo/_base/declare,dojo/_base/connect,dojo/_base/array,dojo/dom-geometry,dojo/_base/fx,dojo/fx,dojo/sniff,./Base,./_PlotEvents,dojo/_base/Color,dojox/color/_base,./common,../axis2d/common,dojox/gfx,dojox/gfx/matrix,dojox/gfx/fx,dojox/lang/functional,dojox/lang/utils,dojo/fx/easing".split(","),function(z,T,I,J,N,K,U,V,W,X,Y,O,v,P,A,L,Q,R,S,D){function Z(a){a=(new O.Color(a)).toHsl();0==a.s?a.l=50>a.l?100:0:(a.s=100,a.l=50>a.l?75:75<a.l?50:a.l-50>75-a.l?50:75);a=O.fromHsl(a);
a.a=0.7;return a}return T("dojox.charting.plot2d.Spider",[W,X],{defaultParams:{labels:!0,ticks:!1,fixed:!0,precision:1,labelOffset:-10,labelStyle:"default",htmlLabels:!0,startAngle:-90,divisions:3,axisColor:"",axisWidth:0,spiderColor:"",spiderWidth:0,seriesWidth:0,seriesFillAlpha:0.2,spiderOrigin:0.16,markerSize:3,spiderType:"polygon",animationType:D.backOut,axisTickFont:"",axisTickFontColor:"",axisFont:"",axisFontColor:""},optionalParams:{radius:0,font:"",fontColor:""},constructor:function(a,b){this.opt=
z.clone(this.defaultParams);S.updateWithObject(this.opt,b);S.updateWithPattern(this.opt,b,this.optionalParams);this.dyn=[];this.datas={};this.labelKey=[];this.oldSeriePoints={};this.animations={}},clear:function(){this.inherited(arguments);this.dyn=[];this.axes=[];this.datas={};this.labelKey=[];this.oldSeriePoints={};this.animations={};return this},setAxis:function(a){if(a){if(void 0!=a.opt.min)this.datas[a.name].min=a.opt.min;if(void 0!=a.opt.max)this.datas[a.name].max=a.opt.max}return this},addSeries:function(a){this.series.push(a);
for(var b in a.data){var d=a.data[b],e=this.datas[b];e?(e.vlist.push(d),e.min=Math.min(e.min,d),e.max=Math.max(e.max,d)):(e="__"+b,this.axes.push(e),this[e]=b,this.datas[b]={min:d,max:d,vlist:[d]})}if(0>=this.labelKey.length)for(b in a.data)this.labelKey.push(b);return this},getSeriesStats:function(){return v.collectSimpleStats(this.series)},render:function(a,b){if(!this.dirty)return this;this.dirty=!1;this.cleanGroup();var d=this.group,e=this.chart.theme;this.resetEvents();if(!this.series||!this.series.length)return this;
var c=this.opt,g=e.axis,f=(a.width-b.l-b.r)/2,i=(a.height-b.t-b.b)/2,j=Math.min(f,i),p=c.font||g.majorTick&&g.majorTick.font||g.tick&&g.tick.font||"normal normal normal 7pt Tahoma",n=c.axisFont||g.tick&&g.tick.titleFont||"normal normal normal 11pt Tahoma",s=c.axisTickFontColor||g.majorTick&&g.majorTick.fontColor||g.tick&&g.tick.fontColor||"silver",E=c.axisFontColor||g.tick&&g.tick.titleFontColor||"black",u=c.axisColor||g.tick&&g.tick.axisColor||"silver",k=c.spiderColor||g.tick&&g.tick.spiderColor||
"silver",$=c.axisWidth||g.stroke&&g.stroke.width||2,w=c.spiderWidth||g.stroke&&g.stroke.width||2,g=c.seriesWidth||g.stroke&&g.stroke.width||2,o=A.normalizedLength(A.splitFontString(n).size),C=L._degToRad(c.startAngle),z,q,v,r,m,x,t=c.spiderOrigin,B=3<=c.divisions?c.divisions:3,D=c.markerSize,I=c.spiderType,K=c.animationType,h=-10>c.labelOffset?c.labelOffset:-10,l;c.labels&&(j=J.map(this.series,function(a){return a.name},this),j=R.foldl1(R.map(j,function(a){return A._base._getTextBox(a,{font:e.series.font}).w},
this),"Math.max(a, b)")/2,j=Math.min(f-2*j,i-o)+h,z=j-h);if("radius"in c)j=c.radius,z=j-h;j/=1.2;f={cx:b.l+f,cy:b.t+i,r:j};for(i=this.series.length-1;0<=i;i--)if(l=this.series[i],!this.dirty&&!l.dirty)e.skip();else if(l.cleanGroup(),h=l.data,null!==h&&(o=this._getObjectLength(h),!q||0>=q.length))if(q=[],v=[],x=[],this._buildPoints(q,o,f,j,C,!0),this._buildPoints(v,o,f,j*t,C,!0),this._buildPoints(x,o,f,z,C),2<B){r=[];m=[];for(h=0;h<B-2;h++)r[h]=[],this._buildPoints(r[h],o,f,j*(t+(1-t)*(h+1)/(B-1)),
C,!0),m[h]=j*(t+(1-t)*(h+1)/(B-1))}o=d.createGroup();u={color:u,width:$};i={color:k,width:w};for(h=q.length-1;0<=h;--h)k=q[h],w={x:k.x+0.2*(k.x-f.cx),y:k.y+0.2*(k.y-f.cy)},k={x:k.x+0.2*(k.x-f.cx)/2,y:k.y+0.2*(k.y-f.cy)/2},o.createLine({x1:f.cx,y1:f.cy,x2:w.x,y2:w.y}).setStroke(u),this._drawArrow(o,w,k,u);o=d.createGroup();for(h=x.length-1;0<=h;--h)k=x[h],w=A._base._getTextBox(this.labelKey[h],{font:n}).w||0,u=this.opt.htmlLabels&&"vml"!=A.renderer?"html":"gfx",k=P.createText[u](this.chart,o,!N.isBodyLtr()&&
"html"==u?k.x+w-a.width:k.x,k.y,"middle",this.labelKey[h],n,E),this.opt.htmlLabels&&this.htmlElements.push(k);n=d.createGroup();if("polygon"==I){if(n.createPolyline(q).setStroke(i),n.createPolyline(v).setStroke(i),0<r.length)for(h=r.length-1;0<=h;--h)n.createPolyline(r[h]).setStroke(i)}else if(n.createCircle({cx:f.cx,cy:f.cy,r:j}).setStroke(i),n.createCircle({cx:f.cx,cy:f.cy,r:j*t}).setStroke(i),0<m.length)for(h=m.length-1;0<=h;--h)n.createCircle({cx:f.cx,cy:f.cy,r:m[h]}).setStroke(i);o=this._getObjectLength(this.datas);
n=d.createGroup();r=0;for(var F in this.datas){m=this.datas[F];q=m.min;m=m.max;m-=q;E=C+2*Math.PI*r/o;for(i=0;i<B;i++)x=q+m*i/(B-1),k=this._getCoordinate(f,j*(t+(1-t)*i/(B-1)),E),x=this._getLabel(x),w=A._base._getTextBox(x,{font:p}).w||0,u=this.opt.htmlLabels&&"vml"!=A.renderer?"html":"gfx",this.opt.htmlLabels&&this.htmlElements.push(P.createText[u](this.chart,n,!N.isBodyLtr()&&"html"==u?k.x+w-a.width:k.x,k.y,"start",x,p,s));r++}this.chart.seriesShapes={};for(i=this.series.length-1;0<=i;i--)if(l=
this.series[i],h=l.data,null!==h){var y=[],G=[];r=0;for(F in h)m=this.datas[F],q=m.min,m=m.max,m-=q,p=h[F],E=C+2*Math.PI*r/o,k=this._getCoordinate(f,j*(t+(1-t)*(p-q)/m),E),y.push(k),G.push({sname:l.name,key:F,data:p}),r++;y[y.length]=y[0];G[G.length]=G[0];var p=this._getBoundary(y),s=e.next("spider",[c,l]),M=l.group,H=A.normalizeColor(s.series.fill),s={color:s.series.fill,width:g};H.a=c.seriesFillAlpha;l.dyn={fill:H,stroke:s};s=this._createSeriesEntry(M,this.oldSeriePoints[l.name]||v,y,H,s,j,t,D,
K);this.chart.seriesShapes[l.name]=s;this.oldSeriePoints[l.name]=y;this._connectEvents({element:"spider_poly",index:i,id:"spider_poly_"+l.name,run:l,plot:this,shape:s.poly,parent:M,brect:p,cx:f.cx,cy:f.cy,cr:j,f:H,s:d});this._connectEvents({element:"spider_plot",index:i,id:"spider_plot_"+l.name,run:l,plot:this,shape:l.group});J.forEach(s.circles,function(a,b){this._connectEvents({element:"spider_circle",index:b,id:"spider_circle_"+l.name+b,run:l,plot:this,shape:a,parent:M,tdata:G[b],cx:y[b].x,cy:y[b].y,
f:H,s:d})},this)}return this},_createSeriesEntry:function(a,b,d,e,c,g,f,i,j){for(var p=a.createPolyline(b).setFill(e).setStroke(c),n=[],g=0;g<b.length;g++)f=b[g],f=a.createCircle({cx:f.x,cy:f.y,r:i}).setFill(e).setStroke(c),n.push(f);e=J.map(d,function(a,c){var d=new K.Animation({duration:1E3,easing:j,curve:[b[c].y,a.y]}),e=n[c];I.connect(d,"onAnimate",function(a){var b=p.getShape();b.points[c].y=a;p.setShape(b);b=e.getShape();b.cy=a;e.setShape(b)});return d});d=J.map(d,function(a,c){var d=new K.Animation({duration:1E3,
easing:j,curve:[b[c].x,a.x]}),e=n[c];I.connect(d,"onAnimate",function(a){var b=p.getShape();b.points[c].x=a;p.setShape(b);b=e.getShape();b.cx=a;e.setShape(b)});return d});U.combine(e.concat(d)).play();return{group:a,poly:p,circles:n}},plotEvent:function(a){var b=a.id?a.id:"default";b in this.animations?(b=this.animations[b],b.anim&&b.anim.stop(!0)):b=this.animations[b]={};if("spider_poly"==a.element){if(!b.color){var d=a.shape.getFill();if(!d||!(d instanceof Y))return;b.color={start:d,end:Z(d)}}var d=
b.color.start,e=b.color.end;if("onmouseout"==a.type)var c=d,d=e,e=c;b.anim=Q.animateFill({shape:a.shape,duration:800,easing:D.backOut,color:{start:d,end:e}});b.anim.play()}else if("spider_circle"==a.element){if("onmouseover"==a.type){e=L.identity;d=1.5;e={type:"rect"};e.x=a.cx;e.y=a.cy;e.w=e.h=1;c=this.chart.getCoords();e.x+=c.x;e.y+=c.y;e.x=Math.round(e.x);e.y=Math.round(e.y);this.aroundRect=e;var g=["after-centered","before-centered"];v.doIfLoaded("dijit/Tooltip",z.hitch(this,function(b){b.show(a.tdata.sname+
"<br/>"+a.tdata.key+"<br/>"+a.tdata.data,this.aroundRect,g)}))}else e=L.scaleAt(1.5,a.cx,a.cy),d=1/1.5,v.doIfLoaded("dijit/Tooltip",z.hitch(this,function(a){this.aroundRect&&a.hide(this.aroundRect)}));c=a.shape.getShape();e=L.scaleAt(1.5,c.cx,c.cy);b.anim=Q.animateTransform({shape:a.shape,duration:200,easing:D.backOut,transform:[{name:"scaleAt",start:[1,c.cx,c.cy],end:[d,c.cx,c.cy]},e]});b.anim.play()}else"spider_plot"==a.element&&"onmouseover"==a.type&&!V("ie")&&a.shape.moveToFront()},_getBoundary:function(a){for(var b=
a[0].x,d=a[0].x,e=a[0].y,c=a[0].y,g=0;g<a.length;g++)var f=a[g],b=Math.max(f.x,b),e=Math.max(f.y,e),d=Math.min(f.x,d),c=Math.min(f.y,c);return{x:d,y:c,width:b-d,height:e-c}},_drawArrow:function(a,b,d,e){var c=Math.sqrt(Math.pow(d.x-b.x,2)+Math.pow(d.y-b.y,2)),g=(d.y-b.y)/c,f=(d.x-b.x)/c;a.createPolyline([b,{x:d.x+c/3*-g,y:d.y+c/3*f},{x:d.x+c/3*g,y:d.y+c/3*-f}]).setFill(e.color).setStroke(e)},_buildPoints:function(a,b,d,e,c,g){for(var f=0;f<b;f++)a.push(this._getCoordinate(d,e,c+2*Math.PI*f/b));g&&
a.push(this._getCoordinate(d,e,c+2*Math.PI))},_getCoordinate:function(a,b,d){return{x:a.cx+b*Math.cos(d),y:a.cy+b*Math.sin(d)}},_getObjectLength:function(a){var b=0;if(z.isObject(a))for(var d in a)b++;return b},_getLabel:function(a){return v.getLabel(a,this.opt.fixed,this.opt.precision)}})});